module.exports = {
	ACTIVATE: 'ACTIVATE',
	DEACTIVATE: 'DEACTIVATE',
	PALLET_ADD: 'PALLET_ADD',
	PALLET_REMOVE: 'PALLET_REMOVE',
	PALLET_SET_ATTACHED: 'PALLET_SET_ATTACHED',
	TEMPLATE_SET: 'TEMPLATE_SET'
};